version: "3.8"
services:
    api:
        container_name: api
        restart: unless-stopped
        build:
            context: ./api
            dockerfile: Dockerfile
        environment:
            NODE_ENV: production
            REDIS_HOST: redis
            REDIS_PORT: 6379
            REDIS_URL: "redis://redis:6379"
        links:
            - redis
        ports:
            - "4000:4000"

    redis:
        container_name: redis
        image: redis/redis-stack-server:latest
        # command: ["redis-server", "--bind", "redis", "--port", "6379"]
        expose:
            - 6379
        volumes:
            - redis-data:/data
            - ./redis/data:/data:ro

    caddy:
        image: caddy:2-alpine
        restart: unless-stopped

        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./caddy/Caddyfile:/etc/caddy/Caddyfile
            - /data/caddy/data:/data # Optional
            - /data/caddy/config:/config # Optional
volumes:
    redis-data:
